// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1OrdersOrderUUIDCancelPost implements POST /api/v1/orders/{order_uuid}/cancel operation.
//
// Отменяет заказ.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) APIV1OrdersOrderUUIDCancelPost(ctx context.Context, params APIV1OrdersOrderUUIDCancelPostParams) (r APIV1OrdersOrderUUIDCancelPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1OrdersOrderUUIDGet implements GET /api/v1/orders/{order_uuid} operation.
//
// Возвращает информацию о заказе по его UUID.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) APIV1OrdersOrderUUIDGet(ctx context.Context, params APIV1OrdersOrderUUIDGetParams) (r APIV1OrdersOrderUUIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1OrdersOrderUUIDPayPost implements POST /api/v1/orders/{order_uuid}/pay operation.
//
// Проводит оплату ранее созданного заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) APIV1OrdersOrderUUIDPayPost(ctx context.Context, req *PayOrderRequest, params APIV1OrdersOrderUUIDPayPostParams) (r APIV1OrdersOrderUUIDPayPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1OrdersPost implements POST /api/v1/orders operation.
//
// Создаёт новый заказ на основе выбранных
// пользователем деталей.
//
// POST /api/v1/orders
func (UnimplementedHandler) APIV1OrdersPost(ctx context.Context, req *CreateOrderRequest) (r APIV1OrdersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
